### PR TITLE
My first Exercises

### PR DESCRIPTION
**Pull request by Jumeb**

### CODE REVIEW

**Comment by kengneruphine** [comment]
Your commit message should include the chapter number and title. For example 
chapter 3, Program structure

**Comment by Jumeb** [comment]
Mentor Good evening, I have just pushed the exercise for chapter three. Pls
check if I did it well

**Comment by kengneruphine** [comment]
I have gone through it and i have given some feedbacks, have u seen it???

**Comment by Jumeb** [comment]
Mentor I have not seen the feedbacks because I don't know where to look it
up

**Comment by kengneruphine** [comment]
Kk , i will have to explain those things when we meet

**Comment by Jumeb** [comment]
Thanks very much

**Pull request merged**
